name: catcat
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flame: ^1.18.0
  flame_audio: ^2.10.2
  hive: 2.2.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame_tiled: ^1.19.0
  audioplayers: ^6.0.0
  flutter_sound: ^9.1.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/14-TileSets/
    - assets/tiles/
    - assets/images/characters/blue-knight/ 
    - assets/images/characters/red-knight/
    - assets/images/characters/green-knight/  
    - assets/images/cat/idle.png
    - assets/images/cat/fin.png
    - assets/images/HUD/
    - assets/images/fondo/fondo1.jpg
    - assets/images/fondo/fondo3.jpg
    - assets/audio/musica_juego.mp3
    - assets/images/logo/logo.jpg
    - assets/images/enemies/Orc/

