// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbulwdtGVTjWaEa6mkprx8efq6S-OMTkc',
    appId: '1:262489715965:web:63a8e07b74a3e6d5fefa94',
    messagingSenderId: '262489715965',
    projectId: 'catcat-7f9b6',
    authDomain: 'catcat-7f9b6.firebaseapp.com',
    storageBucket: 'catcat-7f9b6.appspot.com',
    measurementId: 'G-6P3DS07WK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZH6RhFS7JLIs3YJSnA2FMcK9ezbv4jpY',
    appId: '1:262489715965:android:e38b2f7bc38e8ec8fefa94',
    messagingSenderId: '262489715965',
    projectId: 'catcat-7f9b6',
    storageBucket: 'catcat-7f9b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOs2KF1fAiXRwHQ_knzzoNBz9Uzf-SX3s',
    appId: '1:262489715965:ios:ed56086bcc6b746dfefa94',
    messagingSenderId: '262489715965',
    projectId: 'catcat-7f9b6',
    storageBucket: 'catcat-7f9b6.appspot.com',
    iosClientId: '262489715965-cr0qsjogqnk7ed497a6qhlt246ikf2pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.catcat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOs2KF1fAiXRwHQ_knzzoNBz9Uzf-SX3s',
    appId: '1:262489715965:ios:ed56086bcc6b746dfefa94',
    messagingSenderId: '262489715965',
    projectId: 'catcat-7f9b6',
    storageBucket: 'catcat-7f9b6.appspot.com',
    iosClientId: '262489715965-cr0qsjogqnk7ed497a6qhlt246ikf2pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.catcat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbulwdtGVTjWaEa6mkprx8efq6S-OMTkc',
    appId: '1:262489715965:web:4537b84cdbe45c4cfefa94',
    messagingSenderId: '262489715965',
    projectId: 'catcat-7f9b6',
    authDomain: 'catcat-7f9b6.firebaseapp.com',
    storageBucket: 'catcat-7f9b6.appspot.com',
    measurementId: 'G-LZXL1FJ5VK',
  );

}